### PR TITLE
test folders

### PR DESCRIPTION
**Pull request by germanium-git**

### CODE REVIEW

**Comment by germanium-git** [comment]
Terraform Plan:

```

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # grafana_folder.test_folder1 will be created
  + resource "grafana_folder" "test_folder1" {
      + id                           = (known after apply)
      + prevent_destroy_if_not_empty = false
      + title                        = "Test Folder 1"
      + uid                          = (known after apply)
      + url                          = (known after apply)
    }

  # grafana_folder.test_folder2 will be created
  + resource "grafana_folder" "test_folder2" {
      + id                           = (known after apply)
      + prevent_destroy_if_not_empty = false
      + title                        = "Test Folder 2"
      + uid                          = (known after apply)
      + url                          = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.
```

Plan saved to GH artifacts.

**Review by petr-jamf — APPROVED** [review]

**Comment by germanium-git** [comment]
Terraform Plan:

```

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # grafana_folder.test_folder1 will be created
  + resource "grafana_folder" "test_folder1" {
      + id                           = (known after apply)
      + prevent_destroy_if_not_empty = false
      + title                        = "Test Folder 1"
      + uid                          = (known after apply)
      + url                          = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
Releasing state lock. This may take a few moments...
```

Plan saved to GH artifacts.

**Review by petr-jamf — APPROVED** [review]

**Comment by germanium-git** [comment]
Terraform Plan:

```

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # grafana_folder.test_folder1 will be created
  + resource "grafana_folder" "test_folder1" {
      + id                           = (known after apply)
      + prevent_destroy_if_not_empty = false
      + title                        = "Test_Folder_1"
      + uid                          = (known after apply)
      + url                          = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

Plan saved to GH artifacts.

**Review by petr-jamf — APPROVED** [review]

**Comment by germanium-git** [comment]
Terraform Plan:

```

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # grafana_folder.test_folder1 will be created
  + resource "grafana_folder" "test_folder1" {
      + id                           = (known after apply)
      + prevent_destroy_if_not_empty = false
      + title                        = "Test_Folder 1"
      + uid                          = (known after apply)
      + url                          = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

Plan saved to GH artifacts.

**Review by petr-jamf — APPROVED** [review]

**Comment by germanium-git** [comment]
Terraform Apply:

```
grafana_folder.test_folder1: Creating...
grafana_folder.test_folder1: Creation complete after 0s [id=0:31]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by germanium-git** [comment]
Terraform Plan:

```
grafana_folder.test_folder1: Refreshing state... [id=0:31]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # grafana_folder.folder1 will be created
  + resource "grafana_folder" "folder1" {
      + id                           = (known after apply)
      + prevent_destroy_if_not_empty = false
      + title                        = "TerraformManaged"
      + uid                          = (known after apply)
      + url                          = (known after apply)
    }

  # grafana_folder.test_folder1 will be destroyed
  # (because grafana_folder.test_folder1 is not in configuration)
  - resource "grafana_folder" "test_folder1" {
      - id                           = "0:31" -> null
      - org_id                       = "0" -> null
      - prevent_destroy_if_not_empty = false -> null
      - title                        = "Test_Folder 1" -> null
      - uid                          = "fdc6vjn2xeiv4c" -> null
      - url                          = "https://grafana09ca.grafana.net/dashboards/f/fdc6vjn2xeiv4c/test-folder-1" -> null
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

Plan saved to GH artifacts.

**Review by petr-jamf — APPROVED** [review]

**Comment by germanium-git** [comment]
Terraform Apply:

```
grafana_folder.test_folder1: Destroying... [id=0:31]
grafana_folder.folder1: Creating...
grafana_folder.test_folder1: Destruction complete after 1s
grafana_folder.folder1: Creation complete after 1s [id=0:32]

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.
```

**Pull request merged**
